; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_src_flags = -Os -DUSE_EXFAT=0 -DUSE_LONG_FILE_NAMES=0 -DUSE_SIMPLE_LFN=0 -DUSE_SD_CRC=0 -DUSE_MULTI_BLOCK_SD_IO=0 -DSD_FAT_TYPE=1 -DSDFAT_FILE_TYPE=1 -DCACHE_BLOCK_COUNT=1  -DSPI_DRIVER_SELECT=1
lib_deps = 

[env:sparkfun_promicro8]
platform = atmelavr
board = sparkfun_promicro8
framework = arduino
lib_deps = greiman/SdFat@^2.3.1

[env:teensy_32]
board = teensy31
platform = teensy
framework = arduino
